// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchDaletou(arg1) {
  return window['go']['main']['App']['FetchDaletou'](arg1);
}

export function FetchDaletouHistory(arg1) {
  return window['go']['main']['App']['FetchDaletouHistory'](arg1);
}

export function FetchShuangseqiu(arg1) {
  return window['go']['main']['App']['FetchShuangseqiu'](arg1);
}

export function FetchShuangseqiuHistory(arg1) {
  return window['go']['main']['App']['FetchShuangseqiuHistory'](arg1);
}

export function GetDaletouList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDaletouList'](arg1, arg2, arg3);
}

export function GetDaletouRecommendation(arg1) {
  return window['go']['main']['App']['GetDaletouRecommendation'](arg1);
}

export function GetDaletouStatistics(arg1) {
  return window['go']['main']['App']['GetDaletouStatistics'](arg1);
}

export function GetDaletouTrend(arg1) {
  return window['go']['main']['App']['GetDaletouTrend'](arg1);
}

export function GetShuangseqiuList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetShuangseqiuList'](arg1, arg2, arg3);
}

export function GetShuangseqiuRecommendation(arg1) {
  return window['go']['main']['App']['GetShuangseqiuRecommendation'](arg1);
}

export function GetShuangseqiuStatistics(arg1) {
  return window['go']['main']['App']['GetShuangseqiuStatistics'](arg1);
}

export function GetShuangseqiuTrend(arg1) {
  return window['go']['main']['App']['GetShuangseqiuTrend'](arg1);
}
