// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchDaletou(arg1:string):Promise<any>;

export function FetchDaletouHistory(arg1:number):Promise<any>;

export function FetchShuangseqiu(arg1:string):Promise<any>;

export function FetchShuangseqiuHistory(arg1:number):Promise<any>;

export function GetDaletouList(arg1:number,arg2:number,arg3:string):Promise<any>;

export function GetDaletouRecommendation(arg1:number):Promise<any>;

export function GetDaletouStatistics(arg1:string):Promise<any>;

export function GetDaletouTrend(arg1:number):Promise<any>;

export function GetShuangseqiuList(arg1:number,arg2:number,arg3:string):Promise<any>;

export function GetShuangseqiuRecommendation(arg1:number):Promise<any>;

export function GetShuangseqiuStatistics(arg1:string):Promise<any>;

export function GetShuangseqiuTrend(arg1:number):Promise<any>;
